name: CI - Lint and Molecule Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Molecule and Lint
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🧰 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 🧪 Install dependencies
        run: |
          pip install ansible ansible-lint molecule[docker] yamllint

      - name: ✅ Lint all roles
        run: |
          ansible-lint roles/

      - name: 🧪 Run Molecule tests
        run: |
          cd roles/docker_backup && molecule test || echo "Docker Molecule not configured"
          cd ../../roles/desktop_backup && molecule test || echo "Desktop Molecule not configured"
